### ISSUE TITLE
Upgrade Babel 6 to Babel 7 and/or make ESM detection more accurate

### ISSUE THREAD

**Issue by PatrickShaw** [theKashey/require-control#6]
The current parser being used in `babelIt` is old and doesn't always work with more modern versions of JavaScript that are being used in certain packages. `@testing-library/react` is an example of this.

Here's a minimal replicable example:

```tsx
require('require-control').esm_modules();
require('@testing-library/react');
```

You will then receive the following error:
```
Thrown:
{ [SyntaxError: unknown: Unexpected token (131:4)
  129 |       }
  130 |     },
> 131 |     ...(0, _dom.getQueriesForElement)(baseElement, queries)
      |     ^
  132 |   };
  133 | }
  134 | 
]
```

**EDIT:** As discussed below. This is an issue but the real issue is that `@testing-library/react` shouldn't be detected as using ESM syntax to begin with.

**Comment by theKashey** [comment]
it actually should not have it's "own" babel. Instead, it should try first `@babel`, then `babel`.

The problem is linked to syntax plugin which probably is not babel6 friendly.

**Comment by theKashey** [comment]
PS: why `testing library` is shipped in ESM for node? It is actually a module format detection problem?

**Comment by theKashey** [comment]
Went into the same issue with `@babel/preset-typescript`, not "visible" for `babel-core`

**Comment by PatrickShaw** [comment]
Ah, I think it might be a problem with module format detection (I assumed this package transpiled literally everything).

The default imported JavaScript file exported from `@testing-library/react` is NOT written in ESM so there's two issues:
- `esm_modules()` detects `@testing-library/react` as an ESM module for whatever reason (I haven't looked at why). This is the true issue.
- The version of Babel is too old to understand the syntax that `@testing-library/react` is using

**Comment by theKashey** [comment]
The "detection" is very smart
`return code.indexOf('import ') !== code.indexOf('export ') && code;`
and there is a line at the end of testing library
`// just re-export everything from dom-testing-library`, matching `export `

I should:
- remove comments first
- check for the beginning of a string

**Comment by theKashey** [comment]
Sooner or later, right? 😅
